#!/usr/bin/env bash
# Bash script to install nginx, listening on port 80, returns a webpage when querying nginx at root
apt-get update
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
